### ISSUE TITLE
Does the visualizer need to depend on JAX?

### ISSUE THREAD

**Issue by stephane-caron** [ami-iit/meshcat-viz-python#4]
I went through installing dependencies manually, but my overall question for this project would be: couldn't the visualizer run with only MeshCat as dependency?

**Comment by stephane-caron** [comment]
(Verbose user feedback on!) After installing dependencies manually, I ran into the following import error:

```
RuntimeError: jaxlib is version 0.3.2, but this version of jax requires version >= 0.3.14.
```

I upgraded jaxlib, but then run into the following:

```
RuntimeError: jaxlib version 0.3.20 is newer than and incompatible with jax version 0.3.15. Please update your jax and/or jaxlib packages.
```

So I guess it will be ``jaxlib==0.3.15`` for now. But given other constraints it won't be able to stay at that precise version for long.

**Comment by diegoferigo** [comment]
> I went through installing dependencies manually, but my overall question for this project would be: couldn't the visualizer run with only MeshCat as dependency?

Short answer: yes. Long answer here below.

The visualizer currently needs two piece of information from jaxsim:

1. **The structure of the kinematic tree.** This is necessary [to build the node tree](https://github.com/ami-iit/meshcat-viz-python/blob/9cc3a7c885e860d8601b37f2f2c3d46d292e2c4f/src/meshcat_viz/model_builder.py#L103-L128) used by meshcat. Again, I used the `jaxsim` resource since it was already done, but I plan to move this functionality to [ami-iit/rod](https://github.com/ami-iit/rod).
2. **Computing forward kinematics.** This is necessary to compute the transforms of all links, and again I used `jaxsim` because the algorithm was already implemented there. I agree with you that it would be nice porting the FK algo here in `meshcat-viz` so that the `jaxsim` dependency could be dropped for good. Also this is planned, even if with lower priority.

For what regards the dependency of JAX, I'm still debating. I'm not sure how what could be the performance that could be achieved with pure numpy, and having a JIT-compiled FK algorithm in JAX (even just CPU) could be quite interesting.

Regarding the versioning problems of jax/jaxlib, it's a consequence of what described in https://github.com/ami-iit/jaxsim/issues/12. Sadly JAX deprecated and removed some experimental module that `jaxsim` was using, and I still need to finalize the activity to switch to other resources as documented in https://github.com/ami-iit/jaxsim/issues/12.

**Comment by diegoferigo** [comment]
I made some progress but got stuck again (https://github.com/ami-iit/jaxsim/pull/23). I guess it's time to migrate the jaxsim parser to rod.

**Comment by diegoferigo** [comment]
> Btw, I reproduced the problem of jax/jaxlib versions in https://github.com/ami-iit/jaxsim/actions/runs/3183397287/jobs/5190569189

I isolated the continuous integration part of https://github.com/ami-iit/jaxsim/pull/23 in https://github.com/ami-iit/jaxsim/pull/24. This PR also fixes the `jaxlib` version problem described in https://github.com/ami-iit/meshcat-viz-python/issues/4#issuecomment-1267101159.

**Comment by diegoferigo** [comment]
In https://github.com/ami-iit/meshcat-viz-python/pull/7, I removed the direct dependency from jaxsim. We use external libraries to compute FK, and now it can be done either with jaxsim or idyntree (check [`meshcat_viz.fk`](https://github.com/ami-iit/meshcat-viz-python/tree/main/src/meshcat_viz/fk)).
